# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.TrackCover = QtWidgets.QLabel(self.centralwidget)
        self.TrackCover.setGeometry(QtCore.QRect(10, 10, 200, 200))
        self.TrackCover.setObjectName("TrackCover")
        self.PlayBtn = QtWidgets.QPushButton(self.centralwidget)
        self.PlayBtn.setGeometry(QtCore.QRect(120, 500, 89, 25))
        self.PlayBtn.setObjectName("PlayBtn")
        self.PrevBtn = QtWidgets.QPushButton(self.centralwidget)
        self.PrevBtn.setGeometry(QtCore.QRect(30, 500, 89, 25))
        self.PrevBtn.setObjectName("PrevBtn")
        self.NextBtn = QtWidgets.QPushButton(self.centralwidget)
        self.NextBtn.setGeometry(QtCore.QRect(210, 500, 89, 25))
        self.NextBtn.setObjectName("NextBtn")
        self.UpdateBtn = QtWidgets.QPushButton(self.centralwidget)
        self.UpdateBtn.setGeometry(QtCore.QRect(710, 310, 89, 25))
        self.UpdateBtn.setObjectName("UpdateBtn")
        self.TracksList = QtWidgets.QListWidget(self.centralwidget)
        self.TracksList.setGeometry(QtCore.QRect(250, 0, 551, 311))
        self.TracksList.setObjectName("TracksList")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 410, 91, 17))
        self.label.setObjectName("label")
        self.TrackTitle = QtWidgets.QLabel(self.centralwidget)
        self.TrackTitle.setGeometry(QtCore.QRect(30, 430, 67, 17))
        self.TrackTitle.setObjectName("TrackTitle")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.TrackCover.setText(_translate("MainWindow", "TextLabel"))
        self.PlayBtn.setText(_translate("MainWindow", "Play"))
        self.PrevBtn.setText(_translate("MainWindow", "Prev"))
        self.NextBtn.setText(_translate("MainWindow", "Next"))
        self.UpdateBtn.setText(_translate("MainWindow", "Update"))
        self.label.setText(_translate("MainWindow", "Now playing:"))
        self.TrackTitle.setText(_translate("MainWindow", "TextLabel"))
